/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    svgs: Svg;
    pages: Page;
    work: Work;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    svgs: SvgsSelect<false> | SvgsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    work: WorkSelect<false> | WorkSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'work-page': WorkPage;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'work-page': WorkPageSelect<false> | WorkPageSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    xs?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    sm?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    md?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    lg?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xl?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "svgs".
 */
export interface Svg {
  id: string;
  name: string;
  /**
   * Paste raw SVG markup here. Use fill="currentColor" on any fill attributes so the colour can be controlled via CSS.
   */
  code: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  /**
   * URL path for this page. Use "home" for the homepage (/), otherwise the slug becomes the URL path. Do not change after publishing.
   */
  slug: string;
  /**
   * If enabled, the header will use the dark variant with white text.
   */
  isDark?: boolean | null;
  blocks?:
    | (
        | {
            /**
             * Full-bleed background image or video behind the hero content.
             */
            backgroundMedia?: (string | null) | Media;
            heading: string;
            intro?: string | null;
            buttons?:
              | {
                  label: string;
                  type: 'page' | 'scroll' | 'video';
                  url?: string | null;
                  /**
                   * CSS ID of the target element on the page, without the # symbol.
                   */
                  anchorId?: string | null;
                  videoUrl?: (string | null) | Media;
                  id?: string | null;
                }[]
              | null;
            /**
             * Optional scroll target (e.g. "contact" → #contact). Spaces and special characters are removed automatically.
             */
            anchorId?: string | null;
            /**
             * Which side(s) the vertical padding is applied to.
             */
            paddingWhere?: ('both' | 'top' | 'bottom') | null;
            /**
             * Size of the vertical padding.
             */
            paddingSize?: ('xl' | 'lg' | 'md' | 'sm') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading: string;
            logos: (string | Svg)[];
            /**
             * Optional scroll target (e.g. "contact" → #contact). Spaces and special characters are removed automatically.
             */
            anchorId?: string | null;
            /**
             * Which side(s) the vertical padding is applied to.
             */
            paddingWhere?: ('both' | 'top' | 'bottom') | null;
            /**
             * Size of the vertical padding.
             */
            paddingSize?: ('xl' | 'lg' | 'md' | 'sm') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoList';
          }
        | {
            heading?: string | null;
            works: (string | Work)[];
            /**
             * Label for the link to /work.
             */
            viewAllLabel?: string | null;
            /**
             * Optional scroll target (e.g. "contact" → #contact). Spaces and special characters are removed automatically.
             */
            anchorId?: string | null;
            /**
             * Which side(s) the vertical padding is applied to.
             */
            paddingWhere?: ('both' | 'top' | 'bottom') | null;
            /**
             * Size of the vertical padding.
             */
            paddingSize?: ('xl' | 'lg' | 'md' | 'sm') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'workList';
          }
        | {
            heading: string;
            cards: {
              icon?: (string | null) | Svg;
              heading: string;
              body: string;
              id?: string | null;
            }[];
            /**
             * Optional scroll target (e.g. "contact" → #contact). Spaces and special characters are removed automatically.
             */
            anchorId?: string | null;
            /**
             * Which side(s) the vertical padding is applied to.
             */
            paddingWhere?: ('both' | 'top' | 'bottom') | null;
            /**
             * Size of the vertical padding.
             */
            paddingSize?: ('xl' | 'lg' | 'md' | 'sm') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cardList';
          }
        | {
            heading: string;
            intro?: string | null;
            /**
             * Optional scroll target (e.g. "contact" → #contact). Spaces and special characters are removed automatically.
             */
            anchorId?: string | null;
            /**
             * Which side(s) the vertical padding is applied to.
             */
            paddingWhere?: ('both' | 'top' | 'bottom') | null;
            /**
             * Size of the vertical padding.
             */
            paddingSize?: ('xl' | 'lg' | 'md' | 'sm') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactForm';
          }
        | {
            media: string | Media;
            mediaPosition: 'left' | 'right';
            aspectRatio?: ('auto' | '16/9' | '4/3' | '1/1') | null;
            text: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            /**
             * Optional scroll target (e.g. "contact" → #contact). Spaces and special characters are removed automatically.
             */
            anchorId?: string | null;
            /**
             * Which side(s) the vertical padding is applied to.
             */
            paddingWhere?: ('both' | 'top' | 'bottom') | null;
            /**
             * Size of the vertical padding.
             */
            paddingSize?: ('xl' | 'lg' | 'md' | 'sm') | null;
            verticallyCentreText?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaText';
          }
        | {
            media: string | Media;
            aspectRatio?: ('auto' | '16/9' | '4/3' | '1/1') | null;
            /**
             * Optional scroll target (e.g. "contact" → #contact). Spaces and special characters are removed automatically.
             */
            anchorId?: string | null;
            /**
             * Which side(s) the vertical padding is applied to.
             */
            paddingWhere?: ('both' | 'top' | 'bottom') | null;
            /**
             * Size of the vertical padding.
             */
            paddingSize?: ('xl' | 'lg' | 'md' | 'sm') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'media';
          }
        | {
            quote: string;
            attribution?: string | null;
            /**
             * Optional scroll target (e.g. "contact" → #contact). Spaces and special characters are removed automatically.
             */
            anchorId?: string | null;
            /**
             * Which side(s) the vertical padding is applied to.
             */
            paddingWhere?: ('both' | 'top' | 'bottom') | null;
            /**
             * Size of the vertical padding.
             */
            paddingSize?: ('xl' | 'lg' | 'md' | 'sm') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
      )[]
    | null;
  /**
   * SEO meta description (max 160 characters).
   */
  metaDescription?: string | null;
  /**
   * Social share image (OG). Recommended: 1200×630px.
   */
  ogImage?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work".
 */
export interface Work {
  id: string;
  /**
   * Enable dark mode for this work page.
   */
  isDark?: boolean | null;
  title: string;
  client: string;
  /**
   * Public-facing project name. Used on listing cards and in structured data.
   */
  projectName: string;
  /**
   * Auto-generated from the title. Do not change after publishing.
   */
  slug: string;
  /**
   * Image or video shown on the work listing card.
   */
  listingMedia: string | Media;
  /**
   * Hero media on the detail page. Falls back to listing media if not set.
   */
  heroMedia?: (string | null) | Media;
  services?:
    | {
        service: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional link to the live project.
   */
  url?: string | null;
  body?:
    | (
        | {
            media: string | Media;
            mediaPosition: 'left' | 'right';
            aspectRatio?: ('auto' | '16/9' | '4/3' | '1/1') | null;
            text: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            /**
             * Optional scroll target (e.g. "contact" → #contact). Spaces and special characters are removed automatically.
             */
            anchorId?: string | null;
            /**
             * Which side(s) the vertical padding is applied to.
             */
            paddingWhere?: ('both' | 'top' | 'bottom') | null;
            /**
             * Size of the vertical padding.
             */
            paddingSize?: ('xl' | 'lg' | 'md' | 'sm') | null;
            verticallyCentreText?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaText';
          }
        | {
            media: string | Media;
            aspectRatio?: ('auto' | '16/9' | '4/3' | '1/1') | null;
            /**
             * Optional scroll target (e.g. "contact" → #contact). Spaces and special characters are removed automatically.
             */
            anchorId?: string | null;
            /**
             * Which side(s) the vertical padding is applied to.
             */
            paddingWhere?: ('both' | 'top' | 'bottom') | null;
            /**
             * Size of the vertical padding.
             */
            paddingSize?: ('xl' | 'lg' | 'md' | 'sm') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'media';
          }
        | {
            quote: string;
            attribution?: string | null;
            /**
             * Optional scroll target (e.g. "contact" → #contact). Spaces and special characters are removed automatically.
             */
            anchorId?: string | null;
            /**
             * Which side(s) the vertical padding is applied to.
             */
            paddingWhere?: ('both' | 'top' | 'bottom') | null;
            /**
             * Size of the vertical padding.
             */
            paddingSize?: ('xl' | 'lg' | 'md' | 'sm') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
      )[]
    | null;
  /**
   * Pin this entry to the homepage WorkList block.
   */
  featured?: boolean | null;
  /**
   * SEO meta description (max 160 characters). Defaults to "Client — Title".
   */
  metaDescription?: string | null;
  /**
   * Social share image (OG). Recommended: 1200×630px. Falls back to hero/listing media.
   */
  ogImage?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'svgs';
        value: string | Svg;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'work';
        value: string | Work;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        xs?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        sm?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        md?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        lg?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xl?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "svgs_select".
 */
export interface SvgsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  isDark?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              backgroundMedia?: T;
              heading?: T;
              intro?: T;
              buttons?:
                | T
                | {
                    label?: T;
                    type?: T;
                    url?: T;
                    anchorId?: T;
                    videoUrl?: T;
                    id?: T;
                  };
              anchorId?: T;
              paddingWhere?: T;
              paddingSize?: T;
              id?: T;
              blockName?: T;
            };
        logoList?:
          | T
          | {
              heading?: T;
              logos?: T;
              anchorId?: T;
              paddingWhere?: T;
              paddingSize?: T;
              id?: T;
              blockName?: T;
            };
        workList?:
          | T
          | {
              heading?: T;
              works?: T;
              viewAllLabel?: T;
              anchorId?: T;
              paddingWhere?: T;
              paddingSize?: T;
              id?: T;
              blockName?: T;
            };
        cardList?:
          | T
          | {
              heading?: T;
              cards?:
                | T
                | {
                    icon?: T;
                    heading?: T;
                    body?: T;
                    id?: T;
                  };
              anchorId?: T;
              paddingWhere?: T;
              paddingSize?: T;
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              heading?: T;
              intro?: T;
              anchorId?: T;
              paddingWhere?: T;
              paddingSize?: T;
              id?: T;
              blockName?: T;
            };
        mediaText?:
          | T
          | {
              media?: T;
              mediaPosition?: T;
              aspectRatio?: T;
              text?: T;
              anchorId?: T;
              paddingWhere?: T;
              paddingSize?: T;
              verticallyCentreText?: T;
              id?: T;
              blockName?: T;
            };
        media?:
          | T
          | {
              media?: T;
              aspectRatio?: T;
              anchorId?: T;
              paddingWhere?: T;
              paddingSize?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              quote?: T;
              attribution?: T;
              anchorId?: T;
              paddingWhere?: T;
              paddingSize?: T;
              id?: T;
              blockName?: T;
            };
      };
  metaDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work_select".
 */
export interface WorkSelect<T extends boolean = true> {
  isDark?: T;
  title?: T;
  client?: T;
  projectName?: T;
  slug?: T;
  listingMedia?: T;
  heroMedia?: T;
  services?:
    | T
    | {
        service?: T;
        id?: T;
      };
  url?: T;
  body?:
    | T
    | {
        mediaText?:
          | T
          | {
              media?: T;
              mediaPosition?: T;
              aspectRatio?: T;
              text?: T;
              anchorId?: T;
              paddingWhere?: T;
              paddingSize?: T;
              verticallyCentreText?: T;
              id?: T;
              blockName?: T;
            };
        media?:
          | T
          | {
              media?: T;
              aspectRatio?: T;
              anchorId?: T;
              paddingWhere?: T;
              paddingSize?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              quote?: T;
              attribution?: T;
              anchorId?: T;
              paddingWhere?: T;
              paddingSize?: T;
              id?: T;
              blockName?: T;
            };
      };
  featured?: T;
  metaDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  contactName?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  socialLinks?:
    | {
        platform: 'instagram' | 'linkedin';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Used in structured data (JSON-LD). Separate from the favicon.
   */
  logo?: (string | null) | Media;
  /**
   * The kit ID from use.typekit.net — e.g. "qzh8ztg". Leave blank to disable.
   */
  adobeFontsId?: string | null;
  /**
   * When unchecked, a noindex meta tag and a blocking robots.txt are served. Enable only when the site is ready to go public.
   */
  allowIndexing?: boolean | null;
  legalLinks?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-page".
 */
export interface WorkPage {
  id: string;
  heading?: string | null;
  intro?: string | null;
  blocks?:
    | (
        | {
            heading: string;
            logos: (string | Svg)[];
            /**
             * Optional scroll target (e.g. "contact" → #contact). Spaces and special characters are removed automatically.
             */
            anchorId?: string | null;
            /**
             * Which side(s) the vertical padding is applied to.
             */
            paddingWhere?: ('both' | 'top' | 'bottom') | null;
            /**
             * Size of the vertical padding.
             */
            paddingSize?: ('xl' | 'lg' | 'md' | 'sm') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoList';
          }
        | {
            heading: string;
            cards: {
              icon?: (string | null) | Svg;
              heading: string;
              body: string;
              id?: string | null;
            }[];
            /**
             * Optional scroll target (e.g. "contact" → #contact). Spaces and special characters are removed automatically.
             */
            anchorId?: string | null;
            /**
             * Which side(s) the vertical padding is applied to.
             */
            paddingWhere?: ('both' | 'top' | 'bottom') | null;
            /**
             * Size of the vertical padding.
             */
            paddingSize?: ('xl' | 'lg' | 'md' | 'sm') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cardList';
          }
        | {
            heading: string;
            intro?: string | null;
            /**
             * Optional scroll target (e.g. "contact" → #contact). Spaces and special characters are removed automatically.
             */
            anchorId?: string | null;
            /**
             * Which side(s) the vertical padding is applied to.
             */
            paddingWhere?: ('both' | 'top' | 'bottom') | null;
            /**
             * Size of the vertical padding.
             */
            paddingSize?: ('xl' | 'lg' | 'md' | 'sm') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactForm';
          }
        | {
            media: string | Media;
            mediaPosition: 'left' | 'right';
            aspectRatio?: ('auto' | '16/9' | '4/3' | '1/1') | null;
            text: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            /**
             * Optional scroll target (e.g. "contact" → #contact). Spaces and special characters are removed automatically.
             */
            anchorId?: string | null;
            /**
             * Which side(s) the vertical padding is applied to.
             */
            paddingWhere?: ('both' | 'top' | 'bottom') | null;
            /**
             * Size of the vertical padding.
             */
            paddingSize?: ('xl' | 'lg' | 'md' | 'sm') | null;
            verticallyCentreText?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mediaText';
          }
        | {
            media: string | Media;
            aspectRatio?: ('auto' | '16/9' | '4/3' | '1/1') | null;
            /**
             * Optional scroll target (e.g. "contact" → #contact). Spaces and special characters are removed automatically.
             */
            anchorId?: string | null;
            /**
             * Which side(s) the vertical padding is applied to.
             */
            paddingWhere?: ('both' | 'top' | 'bottom') | null;
            /**
             * Size of the vertical padding.
             */
            paddingSize?: ('xl' | 'lg' | 'md' | 'sm') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'media';
          }
        | {
            quote: string;
            attribution?: string | null;
            /**
             * Optional scroll target (e.g. "contact" → #contact). Spaces and special characters are removed automatically.
             */
            anchorId?: string | null;
            /**
             * Which side(s) the vertical padding is applied to.
             */
            paddingWhere?: ('both' | 'top' | 'bottom') | null;
            /**
             * Size of the vertical padding.
             */
            paddingSize?: ('xl' | 'lg' | 'md' | 'sm') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'quote';
          }
      )[]
    | null;
  /**
   * SEO meta description (max 160 characters).
   */
  metaDescription?: string | null;
  /**
   * Social share image (OG). Recommended: 1200×630px.
   */
  ogImage?: (string | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: string;
  links?:
    | {
        label: string;
        type: 'page' | 'work' | 'url';
        page?: (string | null) | Page;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional call-to-action button shown at the end of the nav.
   */
  button: {
    enabled?: boolean | null;
    label?: string | null;
    type: 'page' | 'work' | 'url';
    page?: (string | null) | Page;
    url?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  contactName?: T;
  contactEmail?: T;
  contactPhone?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  logo?: T;
  adobeFontsId?: T;
  allowIndexing?: T;
  legalLinks?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "work-page_select".
 */
export interface WorkPageSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  blocks?:
    | T
    | {
        logoList?:
          | T
          | {
              heading?: T;
              logos?: T;
              anchorId?: T;
              paddingWhere?: T;
              paddingSize?: T;
              id?: T;
              blockName?: T;
            };
        cardList?:
          | T
          | {
              heading?: T;
              cards?:
                | T
                | {
                    icon?: T;
                    heading?: T;
                    body?: T;
                    id?: T;
                  };
              anchorId?: T;
              paddingWhere?: T;
              paddingSize?: T;
              id?: T;
              blockName?: T;
            };
        contactForm?:
          | T
          | {
              heading?: T;
              intro?: T;
              anchorId?: T;
              paddingWhere?: T;
              paddingSize?: T;
              id?: T;
              blockName?: T;
            };
        mediaText?:
          | T
          | {
              media?: T;
              mediaPosition?: T;
              aspectRatio?: T;
              text?: T;
              anchorId?: T;
              paddingWhere?: T;
              paddingSize?: T;
              verticallyCentreText?: T;
              id?: T;
              blockName?: T;
            };
        media?:
          | T
          | {
              media?: T;
              aspectRatio?: T;
              anchorId?: T;
              paddingWhere?: T;
              paddingSize?: T;
              id?: T;
              blockName?: T;
            };
        quote?:
          | T
          | {
              quote?: T;
              attribution?: T;
              anchorId?: T;
              paddingWhere?: T;
              paddingSize?: T;
              id?: T;
              blockName?: T;
            };
      };
  metaDescription?: T;
  ogImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  links?:
    | T
    | {
        label?: T;
        type?: T;
        page?: T;
        url?: T;
        id?: T;
      };
  button?:
    | T
    | {
        enabled?: T;
        label?: T;
        type?: T;
        page?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}